### ISSUE TITLE
Материалы

### ISSUE THREAD

**Issue by alexbaumgertner** [easy-deep-learning/structure-and-Interpretation-of-js#1]
https://astexplorer.net
http://esprima.org/demo/parse
https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs
https://ru.wikipedia.org/wiki/Формальный_язык

**Comment by dmitrylebedev** [comment]
Посоветовали: https://www.goodreads.com/book/show/703102.Compilers

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/watch?v=2pL28CcEijU

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/watch?v=lTWGoL1N-Kc

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/watch?v=ecIWPzGEbFc

**Comment by alexbaumgertner** [comment]
https://events.yandex.ru/lib/talks/548/ JavaScript: Базовые знания

**Comment by alexbaumgertner** [comment]
https://events.yandex.ru/lib/talks/1692/

**Comment by alexbaumgertner** [comment]
https://events.yandex.ru/lib/talks/542/

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/watch?v=QHs55-5FzgA

**Comment by alexbaumgertner** [comment]
The Digital Abstraction

https://www.youtube.com/watch?v=bDjLIcCV1hI&list=PLrRW1w6CGAcXbMtDFj205vALOGmiRc82-#t=50.890965866

**Comment by alexbaumgertner** [comment]
SICP

- http://www.sicpdistilled.com
- http://sarabander.github.io/sicp/html/index.xhtml
- https://mitpress.mit.edu/sicp/full-text/book/book-Z-H-4.html#%_toc_start
- http://www.comp.nus.edu.sg/~cs1101s/sicp/

**Comment by alexbaumgertner** [comment]
https://leanpub.com/computer-science-distilled

**Comment by alexbaumgertner** [comment]
https://leanpub.com/create_languages

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/playlist?list=PLFB9EC7B8FE963EB8

**Comment by alexbaumgertner** [comment]
https://www.youtube.com/watch?v=dXN0l3uUSCE&list=PLrRW1w6CGAcXbMtDFj205vALOGmiRc82-&index=21

**Comment by alexbaumgertner** [comment]
https://medium.com/dailyjs/gentle-introduction-into-compilers-part-1-lexical-analysis-and-scanner-733246be6738
